/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 12 16:27:00 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Aluno_ESTest extends Aluno_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Aluno aluno0 = new Aluno((String) null, "Aluno{nome='");
      aluno0.setNota((String) null, 1.0);
      double double0 = aluno0.incrementaNota((String) null, 1.0);
      assertEquals(2.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Aluno aluno0 = new Aluno("", "NotaInvalidaException");
      aluno0.setNota("", 20.0);
      assertEquals("NotaInvalidaException", aluno0.getNumero());
      assertEquals("", aluno0.getNome());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      aluno0.incrementaNota("", 20.0);
      double double0 = aluno0.incrementaNota("Aluno{nome='', numero=null}", 20.0);
      assertEquals(20.0, double0, 0.01);
      
      double double1 = aluno0.media();
      assertEquals(20.0, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      Aluno aluno1 = new Aluno(aluno0);
      assertTrue(aluno1.equals((Object)aluno0));
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      String string0 = aluno0.getNumero();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Aluno aluno0 = new Aluno("", "");
      String string0 = aluno0.getNumero();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      String string0 = aluno0.getNome();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Aluno aluno0 = new Aluno("", "");
      String string0 = aluno0.getNome();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Aluno aluno0 = null;
      try {
        aluno0 = new Aluno((Aluno) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Aluno", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      Aluno aluno1 = new Aluno("Aluno{nome='null', numero=null}", "Aluno{nome='null', numero=null}");
      boolean boolean0 = aluno0.equals(aluno1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      boolean boolean0 = aluno0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      boolean boolean0 = aluno0.equals(aluno0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      boolean boolean0 = aluno0.equals("Nota inv\u00E1lida");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      try { 
        aluno0.incrementaNota("Aluno{nome='null', numero=null}", 2084.853834226);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Nota inv\u00E1lida
         //
         verifyException("Aluno", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      try { 
        aluno0.incrementaNota("}iCBwuo,z!F#O9x", (-1456.7529429752506));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Nota inv\u00E1lida
         //
         verifyException("Aluno", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Aluno aluno0 = new Aluno("Nota inv\u00E1lida", "Aluno{nome='");
      aluno0.incrementaNota("Nota inv\u00E1lida", 0.0);
      double double0 = aluno0.incrementaNota("Nota inv\u00E1lida", 0.0);
      assertEquals("Nota inv\u00E1lida", aluno0.getNome());
      assertEquals(0.0, double0, 0.01);
      assertEquals("Aluno{nome='", aluno0.getNumero());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      try { 
        aluno0.setNota("Aluno{nome='null', numero=null}", 3238.1812330308894);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Nota inv\u00E1lida
         //
         verifyException("Aluno", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      aluno0.setNota("p", 0.0);
      assertNull(aluno0.getNome());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      try { 
        aluno0.setNota("", (-79.24830306728283));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Nota inv\u00E1lida
         //
         verifyException("Aluno", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      double double0 = aluno0.getNota("YpX6F]P3}Ee)");
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Aluno aluno0 = new Aluno("Nota inv\u00E1lida", "Aluno{nome='");
      double double0 = aluno0.media();
      assertEquals(0.0, double0, 0.01);
      assertEquals("Nota inv\u00E1lida", aluno0.getNome());
      assertEquals("Aluno{nome='", aluno0.getNumero());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Aluno aluno0 = new Aluno("Nota inv\u00E1lida", "Aluno{nome='");
      Aluno aluno1 = aluno0.clone();
      assertEquals("Nota inv\u00E1lida", aluno1.getNome());
      assertEquals("Aluno{nome='", aluno1.getNumero());
      assertTrue(aluno1.equals((Object)aluno0));
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Aluno aluno0 = new Aluno("Nota inv\u00E1lida", "Aluno{nome='");
      String string0 = aluno0.getNumero();
      assertEquals("Aluno{nome='", string0);
      assertEquals("Nota inv\u00E1lida", aluno0.getNome());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Aluno aluno0 = new Aluno("Nota inv\u00E1lida", "Aluno{nome='");
      String string0 = aluno0.getNome();
      assertEquals("Nota inv\u00E1lida", string0);
      assertEquals("Aluno{nome='", aluno0.getNumero());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Aluno aluno0 = new Aluno("Nota inv\u00E1lida", "Aluno{nome='");
      String string0 = aluno0.toString();
      assertEquals("Aluno{nome='Nota inv\u00E1lida', numero=Aluno{nome='}", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      double double0 = aluno0.incrementaNota("}iCBwuo,z!F#O9x", 8.699875375180822);
      assertEquals(8.699875375180822, double0, 0.01);
      
      double double1 = aluno0.getNota("}iCBwuo,z!F#O9x");
      assertEquals(8.699875375180822, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Aluno aluno0 = new Aluno("Nota inv\u00E1lida", "Aluno{nome='");
      assertEquals("Aluno{nome='", aluno0.getNumero());
      
      aluno0.setNumero("");
      assertEquals("Nota inv\u00E1lida", aluno0.getNome());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Aluno aluno0 = new Aluno("Nota inv\u00E1lida", "Aluno{nome='");
      assertEquals("Nota inv\u00E1lida", aluno0.getNome());
      
      aluno0.setNome("Nota inv\u00E1lida");
      assertEquals("Aluno{nome='", aluno0.getNumero());
  }
}
