/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 12 16:45:30 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Aluno_ESTest extends Aluno_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      double double0 = aluno0.incrementaNota("Dv1=N)", 20.0);
      assertEquals(20.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Aluno aluno0 = new Aluno("", "NotaInvalidaException");
      aluno0.setNota("", 20.0);
      assertEquals("NotaInvalidaException", aluno0.getNumero());
      assertEquals("", aluno0.getNome());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Aluno aluno0 = new Aluno("zBlgkr!ur1~Z!Dq", "");
      aluno0.setNota("n", 0.0);
      assertEquals("zBlgkr!ur1~Z!Dq", aluno0.getNome());
      assertEquals("", aluno0.getNumero());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Aluno aluno0 = new Aluno("", "");
      aluno0.setNota("", 1.0);
      double double0 = aluno0.incrementaNota("#JdkZM[8E$", 0.0);
      assertEquals(0.0, double0, 0.01);
      
      double double1 = aluno0.media();
      assertEquals(0.5, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      Aluno aluno1 = new Aluno(aluno0);
      assertTrue(aluno1.equals((Object)aluno0));
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      String string0 = aluno0.getNumero();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Aluno aluno0 = new Aluno("", "");
      String string0 = aluno0.getNumero();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      aluno0.setNome("Aluno{nome='");
      String string0 = aluno0.getNome();
      assertEquals("Aluno{nome='", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Aluno aluno0 = new Aluno("", "");
      String string0 = aluno0.getNome();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Aluno aluno0 = null;
      try {
        aluno0 = new Aluno((Aluno) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Aluno", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      boolean boolean0 = aluno0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Aluno aluno0 = new Aluno("4gKE+&]R", "4gKE+&]R");
      boolean boolean0 = aluno0.equals(aluno0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Aluno aluno0 = new Aluno("", "");
      boolean boolean0 = aluno0.equals("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      try { 
        aluno0.incrementaNota(",11tu", (-10.393399697404032));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Nota inv\u00E1lida
         //
         verifyException("Aluno", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Aluno aluno0 = new Aluno("4gKE+&]R", "4gKE+&]R");
      aluno0.setNota("4gKE+&]R", 9.3991);
      aluno0.incrementaNota("4gKE+&]R", 9.3991);
      try { 
        aluno0.incrementaNota("4gKE+&]R", 9.3991);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Nota inv\u00E1lida
         //
         verifyException("Aluno", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      try { 
        aluno0.setNota("XtO(]cLfx c", 1113.8197717744877);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Nota inv\u00E1lida
         //
         verifyException("Aluno", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      try { 
        aluno0.setNota("Aluno{nome='null', numero=null}", (-739.4221300214774));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Nota inv\u00E1lida
         //
         verifyException("Aluno", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      double double0 = aluno0.getNota("");
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Aluno aluno0 = new Aluno("4gKE+&]R", "4gKE+&]R");
      aluno0.setNota("4gKE+&]R", 9.3991);
      double double0 = aluno0.getNota("4gKE+&]R");
      assertEquals(9.3991, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      double double0 = aluno0.media();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      Aluno aluno1 = aluno0.clone();
      boolean boolean0 = aluno1.equals(aluno0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Aluno aluno0 = new Aluno("4gKE+&]R", "4gKE+&]R");
      String string0 = aluno0.getNumero();
      assertEquals("4gKE+&]R", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      String string0 = aluno0.getNome();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      String string0 = aluno0.toString();
      assertEquals("Aluno{nome='null', numero=null}", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Aluno aluno0 = new Aluno();
      aluno0.setNumero("XtO(]cLfx c");
      assertNull(aluno0.getNome());
  }
}
