/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 12 16:45:39 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AlunoInexistenteException_ESTest extends AlunoInexistenteException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AlunoInexistenteException alunoInexistenteException0 = new AlunoInexistenteException("");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AlunoInexistenteException alunoInexistenteException0 = new AlunoInexistenteException();
  }
}
