/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 12 16:46:23 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Turma_ESTest extends Turma_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Turma turma0 = new Turma();
      Aluno aluno0 = new Aluno("}.8Mr", "iUnmi![VD5)EIq");
      aluno0.incrementaNota("-:l6W614bQb", 10.0);
      turma0.addAluno(aluno0);
      List<Aluno> list0 = turma0.reprovados();
      assertFalse(list0.contains(aluno0));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Turma turma0 = new Turma();
      Aluno aluno0 = new Aluno((String) null, "E(wcwlU`79[Wh");
      turma0.addAluno(aluno0);
      Aluno aluno1 = new Aluno("t;viE", "t;viE");
      aluno1.setNota("t;viE", 20.0);
      turma0.addAluno(aluno1);
      double double0 = turma0.media();
      assertEquals(10.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Turma turma0 = new Turma();
      Aluno aluno0 = new Aluno((String) null, "E(wcwlU`79[Wh");
      aluno0.setNota("t;viE", 20.0);
      turma0.addAluno(aluno0);
      double double0 = turma0.media();
      assertEquals(20.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Turma turma0 = new Turma();
      Aluno aluno0 = new Aluno("'{0 ZPE_r", "'{0 ZPE_r");
      turma0.addAluno(aluno0);
      List<Aluno> list0 = turma0.getAlunos();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Turma turma0 = new Turma();
      Aluno aluno0 = new Aluno(", numr=", ", numr=");
      turma0.addAluno(aluno0);
      Aluno aluno1 = turma0.getAluno(", numr=");
      assertNotSame(aluno1, aluno0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Turma turma0 = new Turma();
      Aluno aluno0 = new Aluno("'{0 ZPE_r", "'{0 ZPE_r");
      turma0.addAluno(aluno0);
      boolean boolean0 = turma0.containsAluno("'{0 ZPE_r");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedList<Aluno> linkedList0 = new LinkedList<Aluno>();
      Aluno aluno0 = new Aluno();
      linkedList0.add(aluno0);
      Turma turma0 = new Turma(linkedList0);
      // Undeclared exception!
      try { 
        turma0.removeAluno("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Turma turma0 = new Turma();
      Aluno aluno0 = new Aluno();
      turma0.addAluno(aluno0);
      // Undeclared exception!
      try { 
        turma0.getAluno("e=uOf1ahm*");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Turma turma0 = new Turma();
      Aluno aluno0 = new Aluno();
      turma0.addAluno(aluno0);
      // Undeclared exception!
      try { 
        turma0.containsAluno("LlK^b");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Turma turma0 = new Turma();
      Aluno aluno0 = new Aluno();
      turma0.addAluno(aluno0);
      // Undeclared exception!
      try { 
        turma0.addAluno(aluno0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Turma turma0 = new Turma();
      turma0.setAlunos((List<Aluno>) null);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Turma turma0 = new Turma();
      boolean boolean0 = turma0.containsAluno("'{0 ZPE_r");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Turma turma0 = new Turma();
      Aluno aluno0 = new Aluno("Cl43y\"7hvH", "Cl43y\"7hvH");
      aluno0.setNota("Cl43y\"7hvH", 20.0);
      turma0.addAluno(aluno0);
      List<Aluno> list0 = turma0.reprovados();
      assertFalse(list0.contains(aluno0));
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Turma turma0 = new Turma();
      double double0 = turma0.media();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Turma turma0 = new Turma();
      Aluno aluno0 = new Aluno((String) null, "E(wcwlU`79[Wh");
      turma0.addAluno(aluno0);
      double double0 = turma0.media();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Turma turma0 = new Turma();
      Aluno aluno0 = new Aluno("NotaInebiaExc2tn", "NotaInebiaExc2tn");
      turma0.addAluno(aluno0);
      LinkedList<Aluno> linkedList0 = new LinkedList<Aluno>();
      List<Aluno> list0 = turma0.reprovados();
      linkedList0.addAll((Collection<? extends Aluno>) list0);
      linkedList0.add(aluno0);
      turma0.setAlunos(linkedList0);
      turma0.removeAluno("NotaInebiaExc2tn");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Turma turma0 = new Turma();
      Aluno aluno0 = new Aluno((String) null, "E(wcwlU`79[Wh");
      turma0.addAluno(aluno0);
      try { 
        turma0.removeAluno("T\rma");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Aluno inexistente
         //
         verifyException("Turma", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Turma turma0 = new Turma();
      turma0.addAluno((Aluno) null);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Turma turma0 = new Turma((Turma) null);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Turma turma0 = new Turma();
      Turma turma1 = new Turma(turma0);
      assertFalse(turma1.equals((Object)turma0));
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Turma turma0 = new Turma();
      List<Aluno> list0 = turma0.getAlunos();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Turma turma0 = new Turma();
      Aluno aluno0 = new Aluno("NotaInebiaExc2tn", "NotaInebiaExc2tn");
      turma0.addAluno(aluno0);
      turma0.addAluno(aluno0);
      assertEquals("NotaInebiaExc2tn", aluno0.getNome());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Turma turma0 = new Turma();
      try { 
        turma0.getAluno("NotaInebiaExc2tn");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Aluno inexistente
         //
         verifyException("Turma", e);
      }
  }
}
